name: build

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Check android tests
        run: ./gradlew :app:testDebugUnitTest --tests "com.rcl.connector.KoinCheck.checkKoinModule
      - name: Build android app
        run: |
          ./gradlew assembleRelease
      - name: Upload android builds
        uses: actions/upload-artifact@v3
        with:
          name: connector.apk
          path: composeApp/build/outputs/apk/release/app-release.apk